name = "ProgressMeter"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "1.6.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "0.7, 1"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Distributed", "InteractiveUtils"]
